export default {
  iconColor: '#33FF5A',
  tintColor: '#2f95dc',
  successColor: '#2db84c',
  headerColor: '#f8f8f8',
  backGround: '#eeeeee',
  whiteColor: '#fff',
  iconBlackHeader: "#383838",
  titleColor: 'black',
  greyColor: '#ccc',
  greenHeader: '#2db84c',
  textWhite: '#fff',
  tabIconDefault: '#ccc',
  iconGrey: '#ccc',
  tabIconSelected: '#2f95dc',
  tabBar: '#fefefe',
  errorBackground: 'red',
  errorText: '#fff',
  warningBackground: '#EAEB5E',
  warningText: '#666804',
  noticeBackground: '#2f95dc',
  noticeText: '#fff',
  backgroundGreen: '#247936',
  primaryColor: '#2f95dc',
  dangerColor: '#b22222',
  defaultColor: '#2b2b28'
};
